spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/easymenu_db}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

