spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5434/easymenu_db}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

    cache:
      type: redis

    redis:
      host: ${DATABASE_REDIS:localhost}
      port: 6379

