spring:
  datasource:
    url: jdbc:mysql://prod-host:3306/easymenu
    username: prod_user
    password: prod_pass

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

cors:
  allowed-origins: https://easymenu.app
