spring:
  profiles:
    active: local
  data:
    web:
          pageable:
            default-page-size: 10
            max-page-size: 100

logging:
  level:
    org.springframework.security: DEBUG

problem:
  stack-trace: false


jackson:
  serialization:
    write-dates-as-timestamps: false
  mapper:
    default-view-inclusion: true

api:
  security:
    token:
      secret: ${JWT_SECRET::my-secret-key}
