spring:
  datasource:
    url: ${DBPROD_URL:jdbc:postgresql://localhost:5433/easymenudb}
    username: ${DBPROD_USERNAME}
    password: ${DBPROD_PASSWORD}
    driver-class-name: org.postgresql.Driver
