spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/easymenu_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lab:
            non_contextual_creation: true
