name: Java CI with Maven

on:
  push:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test
        run: mvn clean test -Dspring.profiles.active=test

      - name: Dockerhub login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t viniciusyr/easymenuapi:latest .

      - name: Push Docker image
        run: docker push viniciusyr/easymenuapi:latest

  deploy:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Pull image from Docker Hub
        run: docker pull viniciusyr/easymenuapi:latest

      - name: Stop and Remove Old Container (if any)
        run: |
          docker stop easymenuapi || true
          docker rm easymenuapi || true

      - name: Run Docker Container
        run: |
          docker run -d \
            --name easymenuapi \
            -e DBPROD_URL=${{ secrets.DBPROD_URL }} \
            -e DBPROD_USERNAME=${{ secrets.DBPROD_USERNAME }} \
            -e DBPROD_PASSWORD=${{ secrets.DBPROD_PASSWORD }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e SPRING_PROFILES_ACTIVE=prod \
            -p 8080:8080 \
            --restart always \
            viniciusyr/easymenuapi:latest