spring:
    datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
        driver-class-name: org.h2.Driver
        username: sa
        password:

    cache:
        type: none

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create-drop

    h2:
        console:
            enabled: true

    main:
        allow-bean-definition-overriding: true

cors:
    allowed-origins: http://localhost
